### PR TITLE
feat: add pong example

### PR DESCRIPTION
**Pull request by RodrigoDornelles**
I'm a beginner at ginga and lua, this is my first game, I made it as a hello world, a simplified view is interesting for other beginners.

I wanted to make a fluid game.

https://github.com/TeleMidia/ginga/assets/29123479/df5d481e-1e0a-4244-88f4-8d1aa986145d

### CODE REVIEW

**Comment by rafael2k** [comment]
Muito legal mesmo @RodrigoDornelles !
Vou dar uma olhadinha antes de mergear.

**Comment by RodrigoDornelles** [comment]
@rafael2k I was trying to solve a bug, reported #190, but it never worked out, I thought of a simpler and more effective solution.

I consider that pong is done, and **tested on real hardware!**

| pong |
| :-: |
| <https://raw.githubusercontent.com/RodrigoDornelles/RodrigoDornelles/master/media/ginga-pong.gif> |

**Comment by RodrigoDornelles** [comment]
@alanlivio @rafael2k não tenho mais ajustes a considerar, está bom no estado que está! inclusive validei em diversos modelos de televisão!

**Comment by rafael2k** [comment]
Merged! Thanks!

**Pull request merged**
